version: "3.2"

services:
  api: 
    build:  ./api 
    ports:
      - 3000:3000
      - 8888:8888
    volumes:
      - ./api/src:/usr/app/src
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DATABASE:
      
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DATABASE:


  




    
