version: "3.2"

services:
  api: 
    build:  ./api 
    environment:
      pg_connection_string: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:3000/${POSTGRES_DATABASE}"
      PORT: 
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/usr/app/src
    depends_on:
      postgres:
        condition: service_healthy
      
      
  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 5
    restart: always
    ports:
     - "5000:5000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: db
      POSTGRES_PORT: 3000


  #store:
  #  image: "postgres:latest"
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U postgres"]
  #    interval: 5s
  #    timeout: 5s
  #    retries: 5


  




    
