version: "3.2"

services:
  api: 
    build:  ./api 
    ports:
      - 8888:8888
    volumes:
      - ./api/src:/usr/app/src
      
      
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
     - "3000:3000"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: db
      POSTGRES_PORT: 3000
    command: -p 3000


  #store:
   # image: "postgres:latest"
    #healthcheck:
     # test: ["CMD-SHELL", "pg_isready -U postgres"]
      #interval: 5s
      #timeout: 5s
      #retries: 5


  




    
